---
title: "analyze_modi"
author: "MSPC"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    highlight: zenburn
    toc: yes
    toc_float: false
    self_contained: true
params:
  root_dir: NULL
  data_dir: NULL
  output_dir: NULL
  metadata: NULL
  config: "None"  # from python. make all the NULLs "None"?
  gct: NULL # not always used
  save_environ: false
---

<style type="text/css">
.main-container {
  max-width: 100% !important;
  margin: auto;
}
</style>

```{r setup, include=T}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages(library(rlang))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(magrittr))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(ComplexHeatmap))
suppressPackageStartupMessages(library(circlize))
suppressPackageStartupMessages(library(reactable))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(here))
library(dendsort)


library(knitr)
myreactable <- function(x, ...) reactable(x, defaultPageSize = 14, searchable = T, compact = T, resizable=T, sortable = T, filterable = T, ...)

(here())

source(file.path(here("R", "lazyloader.R")))
io_tools <- get_tool_env("io")
heatmap_tools <- get_tool_env("heatmap")
util_tools <- get_tool_env("utils")
limma_tools <- get_tool_env("limma")

OUTDIR <- params$output_dir %||% params$data_dir %||% "."
config_file <- params$config %||% file.path(here(), "config", "base.toml")
config <- io_tools$load_config(config_file)

# dist_no_na <- util_tools$dist_no_na
# myzscore <- util_tools$myzscore

# more fine grained params with defaults and validation

knitr::opts_chunk$set(fig.path=file.path(OUTDIR, "modi-figures"))

SAVE_ENVIRON <- params$save_environ %||% FALSE

```

```
metadata should be a tsv file with an expr_file column
```

# load

params:
```{r, label='show-params'}
(params)
```

```{r, label='show-config'}
(config)
```


```{r, label='load-gct'}

if (!is.null(params$gct)){
    gct <- cmapR::parse_gctx(params$gct)
} else {
  cat("no data passed, exiting")
  knitr::knit_exit()
}

OUTNAME <- basename(params$gct) %>% gsub("_n\\d+x\\d+\\.gct", "", .)

```

```{r, label = 'display-meta'}
gct@cdesc %>% myreactable
```

# explore

## heatmap

```{r, label='draw-heatmap', include = F}
.tokeep <- gct %>%
  melt_gct() %>%
  distinct(fifteenmer, .keep_all = T) %>%
  pull(id.x)
subgct <- gct %>% subset_gct(rid = .tokeep) # this is important to reduce redundancy, can be looked up later from other file
gct_z <- util_tools$scale_gct(subgct, group_by = params$zscore_by)




param_grid <- expand.grid(
  cut_by = config$heatmap$cut_by %||% NULL,
  cluster_rows = config$heatmap$cluster_rows %||% TRUE,
  cluster_columns = config$heatmap$cluster_columns %||% FALSE,
  # top_n = config$heatmap$selection$top_n %||% c(20, 40, 60)
  # file_data = file_data
  )

param_grid %>% purrr::map(~{
    cut_by_val <- ..1
    cluster_rows_val <- ..2
    cluster_columns_val <- ..3
    # top_n_val <- ..4
    .cut_by  <- .x
    # print(paste0('cut by is: ', cut_by))
    print(cut_by)
    .outf <- file.path(OUTDIR,
            paste0(OUTNAME, "_heatmap_all_",
            "cut_",
            cut_by_val,
            nrow(gct_z@mat),
            "x",
            ncol(gct_z@mat),
            ".pdf"))
    message(paste0('drawing ', .outf))
    cairo_pdf(.outf,
        width = config$heatmap$fig_width %||% 9,
        height = config$heatmap$fig_height %||% 11
        )
    ht_draw_func <- heatmap_tools$make_heatmap_fromgct(gct_z,
            cut_by = .cut_by,
            cluster_rows = config$heatmap$cluster_rows %||% TRUE,
            cluster_columns = config$heatmap$cluster_columns %||% FALSE,
            show_row_names = FALSE,
            include_row_annotations = FALSE,
            column_title = make.names(basename(params$gct) %>% gsub("_n\\d+x\\d+\\.gct", "", .)),
            meta_to_include = config$heatmap$legend_include %||% NULL,
            meta_to_exclude = config$heatmap$legend_exclude %||% NULL,
    )
    ht <- ht_draw_func() # sets some things at "draw"time
    # ComplexHeatmap::draw(ht)
    dev.off()
    return(ht)
})
```





# limma
```{r, label='limma-setup', cache=F}
library(limma)
if (config$limma$do){

  topTables <- limma_tools$run_limma(gct, config)

}

 # ( contrasts <- limma::makeContrasts(contrast_strings, levels = mod) )
```




```{r, label='topTables'}

toptables2 <- toptables %>% purrr::map(~ {
  assertthat::are_equal(nrow(.x), nrow(dataw))
  bind_cols(
    dataw %>% select(-meta$name),
    .x
  ) %>% arrange(P.Value) %>%
    left_join(data %>% select(
      acc_id,
      lt_lit,
      ms_lit,
      fifteenmer,
      sitename,
      uniprot_id,
      ENSP,
      site_id
    ) %>%
    distinct()
  )

})


toptables2 %>% purrr::iwalk(~ {
  .outdir <- file.path(OUTDIR, "results", "modi")
  if (!fs::dir_exists(.outdir)) fs::dir_create(.outdir)
  .outf <- .y %>% str_replace(" - ", "_minus_")
  .fulloutf <- file.path(.outdir, paste0(make.names(.outf), ".tsv"))

  if (fs::file_exists(.fulloutf) && config$advanced$replace == FALSE) {
    cat(paste0("Skipping ", .fulloutf, " because it exists and replace is FALSE\n"))
    return()
  }
  cat(paste0("Writing ", .fulloutf,'\n'))
  .x %>% write_tsv(.fulloutf)

})
```






```{r, label = 'end'}
if (SAVE_ENVIRON) save.image(file.path(OUTDIR$data_dir, 'merge_modis.RData'))

(loadedNamespaces())
(version)

```
