---
title: "heatmap"
author: "MSPC"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    highlight: zenburn
    toc: yes
    toc_float: false
    self_contained: true
params:
  root_dir: NULL
  data_dir: NULL
  output_dir: NULL
  metadata: NULL
  config: "None"  # from python. make all the NULLs "None"?
  gct: NULL # not always used
  save_env: false
---

<style type="text/css">
.main-container {
  max-width: 100% !important;
  margin: auto;
}
</style>

```{r setup, include=T}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages(library(rlang))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(magrittr))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(ComplexHeatmap))
suppressPackageStartupMessages(library(circlize))
suppressPackageStartupMessages(library(reactable))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(here))
library(dendsort)


library(knitr)
myreactable <- function(x, ...) reactable(x, defaultPageSize = 14, searchable = T, compact = T, resizable=T, sortable = T, filterable = T, ...)

(here())

```

```{r, label='load-tools'}
source(file.path(here("R", "lazyloader.R")))
io_tools <- get_tool_env("io")
util_tools <- get_tool_env("utils")
OUTDIR <- params$output_dir %||% params$data_dir %||% "."
config_file <- params$config %||% file.path(here(), "config", "base.toml")
```

```{r, label='load-params'}
config <- io_tools$load_config(config_file, root_dir = params$root_dir)

# dist_no_na <- util_tools$dist_no_na
# myzscore <- util_tools$myzscore

# more fine grained params with defaults and validation

# knitr::opts_chunk$set(fig.path=file.path(OUTDIR, "modi-figures/"))

SAVE_ENV <- params$save_env %||% FALSE

```
create heatmap from input files
very simple, only does one thing

# load


```{r, label='load-gct'}

gct_file <- params$gct %||% config$gct_file

if (!is.null(gct_file)){
    gct <- cmapR::parse_gctx(gct_file)
} else {
  cat("no data passed, exiting")
  knitr::knit_exit()
}

if (!is.null(config$extra$sample_exclude)) {
  to_exclude <- config$extra$sample_exclude %||% NULL
  to_exclude <- intersect(rownames(gct@cdesc), to_exclude)
  message(paste0("excluding ", length(to_exclude), " samples"))
  to_keep <- setdiff(rownames(gct@cdesc), to_exclude)
  gct <- gct %>% subset_gct(cid = to_keep)
}


OUTNAME <- basename(gct_file) %>% gsub("_n\\d+x\\d+\\.gct", "", .)

```

```{r, label = 'display-meta'}
gct@cdesc %>% myreactable
```

# plot heatmaps

```{r}
gct_z <- util_tools$scale_gct(gct, group_by = config$heatmap$zscore_by)
```

## heatmap

```{r, label='draw-heatmap', cache=FALSE}

heatmap_tools <- get_tool_env("heatmap")

draw_heatmap <- function(...){
  .tokeep <- gct %>%
    melt_gct() %>%
    distinct(fifteenmer, .keep_all = T) %>%
    pull(id.x)
  subgct <- gct %>% subset_gct(rid = .tokeep) # this is important to reduce redundancy, can be looked up later from other file
  gct_z <- util_tools$scale_gct(subgct, group_by = params$zscore_by)

  .outf <- file.path(OUTDIR, paste0(OUTNAME, "_heatmap_all.pdf"))
  message(paste0('drawing ', .outf))
  cairo_pdf(.outf,
      width = 16,
      height = 14
      )
  ht_draw_func <- heatmap_tools$make_heatmap_fromgct(gct_z,
          cut_by = config$heatmap$cut_by %||% NULL,
          cluster_rows = config$heatmap$cluster_rows %||% TRUE,
          cluster_columns = config$heatmap$cluster_columns %||% FALSE,
          show_row_names = TRUE
  )
  ht_draw_func() # sets some things at "draw"time
  # ComplexHeatmap::draw(ht)
  dev.off()
}
```


```{r, label='draw-heatmaps'}




param_grid <- expand.grid(
  cut_by = config$heatmap$cut_by %||% NULL,
  cluster_rows = config$heatmap$cluster_rows %||% TRUE,
  cluster_columns = config$heatmap$cluster_columns %||% FALSE,
  top_n = config$heatmap$selection$top_n %||% c(20, 40, 60)
  )
  print(param_grid)

config$heatmap$selection$file_list %>%
  flatten %>%
  imap(~{
    the_file <- .x
    name <- .y
    if (!file.exists(the_file)){
      message(paste0("file ", the_file, " does not exist"))
      return(NULL)
    }

    print(name)
    print(the_file)
    #

    file_data <- io_tools$read_genelist_file(the_file)
    # Handle file_data if it's a dataframe or list of dataframes
    # Convert to list with original name if it's a single dataframe
    if (is.data.frame(file_data)) file_data <- list("a" = file_data)

    param_grid <- expand.grid(
      cut_by = config$heatmap$cut_by %||% NULL,
      cluster_rows = config$heatmap$cluster_rows %||% TRUE,
      cluster_columns = config$heatmap$cluster_columns %||% FALSE,
      top_n = config$heatmap$selection$top_n %||% c(20, 40, 60)
      # file_data = file_data
      )
      print(param_grid)

    file_data %>% purrr::imap(~{
      file_data_name <- .y
      subname <- paste0(name, "_", file_data_name)
      column_title <- paste0(OUTNAME, "\n", subname)
      file_data_val <- .x

      param_grid %>% purrr::pmap(~{
        cut_by_val <- ..1
        cluster_rows_val <- ..2
        cluster_columns_val <- ..3
        top_n_val <- ..4

        # print(file_data_val)
        print(paste0('\\ntop n val ', top_n_val))

        subsel <- file_data_val # unless we want to filter further by possible column values
        # if ("t_value" %in% colnames(file_data_val)){
        if (length(colnames(file_data_val)) > 1 && (is.numeric(file_data_val[[2]]))){

          .top_vals <- util_tools$select_top_n(
                data = file_data_val,
                sort_column = colnames(file_data_val)[[2]],
                top_n = top_n_val,
                sort_order = "desc")
          # .top_tvals <- file_data_val %>% distinct(t_value) %>% head(n = top_n_val) %>% pull(t_value)
          print(.top_vals)
          subsel <- .top_vals
          # subsel <- file_data_val[ file_data_val[[1]] %in% .top_vals[,1], ] #%>% filter(.data[[1]] %in% .top_vals[,1])
        }


        if (nrow(subsel) == 0){
          message(paste0("no rows in ", subname))
          return(NULL)
        }

        subgct_z <- gct_z %>% subset_gct(rid = subsel$id)
        .nrow <- nrow(subgct_z@mat)
        .ncol <- ncol(subgct_z@mat)
        .outdir <- file.path(OUTDIR, "heatmaps")
        if (!is.null(cut_by_val)){
             .outdir <- file.path(.outdir, paste0('cut_',make.names(cut_by_val)))
        }
        if (!dir.exists(.outdir)) dir.create(.outdir, recursive = TRUE)
        .outf <- file.path(.outdir, make.names(paste0(OUTNAME,
         subname, "_",
          .nrow, 'x', .ncol,
          "_cut_", cut_by_val,
          "cr_", cluster_rows_val,
          "cc_", cluster_columns_val,
           ifelse( !is.null(config$heatmap$zscore_by), config$heatmap$zscore_by, ""),
            ".pdf")))

        if (!is.null(cut_by_val)){
             if (grepl(":", cut_by_val)) cut_by_val <- unlist(strsplit(as.character(cut_by_val), ":"))
        }


        ht_draw_code <- heatmap_tools$make_heatmap_fromgct(
          gct = subgct_z,
          column_title = column_title,
          cut_by = cut_by_val,
          cluster_rows = cluster_rows_val,
          cluster_columns = cluster_columns_val,
          meta_to_include = config$heatmap$legend_include %||% NULL,
          meta_to_exclude = config$heatmap$legend_exclude %||% NULL,
          show_row_names = TRUE,
          include_row_annotations = TRUE,
          optimal_size = TRUE
          )
        height <- 6 + (.nrow * .20)
        width <- 12 + (.ncol * .26)


        message(paste0('drawing ', .outf))
        if (file.exists(.outf) && config$advanced$replace == FALSE){
          message(paste0(.outf, " already exists, skipping"))
          return(NULL)
        }
        tryCatch(
          {
            cairo_pdf(.outf, width = width, height = height)
            ht_draw_code()
            dev.off()
          },
          error = function(e) print(e)
        )

      }) #   end fo pmap
    })  # end of imap
    #
  })
```

```{r, label='heatmap-of-everything'}
# heatmap of everything


param_grid <- expand.grid(
  cut_by = config$heatmap$cut_by %||% NULL,
  cluster_rows = config$heatmap$cluster_rows %||% TRUE,
  cluster_columns = config$heatmap$cluster_columns %||% FALSE
  )

param_grid %>% purrr::pmap(~{
  cut_by_val <- ..1
  cluster_rows_val <- ..2
  cluster_columns_val <- ..3

  ht_draw_code <- heatmap_tools$make_heatmap_fromgct(
    gct = gct_z,
    column_title = "everything",
    cut_by = cut_by_val,
    cluster_rows = cluster_rows_val,
    cluster_columns = cluster_columns_val,
    # cut_by = config$heatmap$cut_by %||% NULL,
    # cluster_rows = config$heatmap$cluster_rows %||% TRUE,
    # cluster_columns = config$heatmap$cluster_columns %||% FALSE,
    meta_to_include = config$heatmap$legend_include %||% NULL,
    meta_to_exclude = config$heatmap$legend_exclude %||% NULL,
    show_row_names = FALSE,
    include_row_annotations = FALSE,
    optimal_size = FALSE
    )
  height <- 9
  width <- 11

  .outdir <- file.path(OUTDIR, "heatmaps")
  if (!dir.exists(.outdir)) dir.create(.outdir, recursive = TRUE)
  .outf <- file.path(.outdir, make.names(paste0(OUTNAME,
    "_",
    nrow(gct_z@mat), 'x', ncol(gct_z@mat),
    "_cut_", cut_by_val,
    "cr_", cluster_rows_val,
    "cc_", cluster_columns_val,
     ifelse( !is.null(config$heatmap$zscore_by), config$heatmap$zscore_by, ""),
      ".pdf")))

  message(paste0('drawing ', .outf))
  if (file.exists(.outf) && config$advanced$replace == FALSE){
    message(paste0(.outf, " already exists, skipping"))
    return(NULL)
  }
  tryCatch(
    {
      cairo_pdf(.outf, width = width, height = height)
      ht_draw_code()
      dev.off()
    },
    error = function(e) stop(e)
  )
})

```



```{r, label = 'end'}
if (SAVE_ENV) save.image(file.path(OUTDIR$data_dir, 'heatmap_draw.RData'))

(loadedNamespaces())
(version)

```



params:
```{r, label='show-params'}
(params)
```

config:
```{r, label='show-config'}
(config)
```
