---
title: "merge_modis"
author: "MSPC"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    highlight: zenburn
    toc: yes
    toc_float: false
    self_contained: true
params:
  root_dir: NULL
  data_dir: NULL
  output_dir: NULL
  metadata: NULL
  config: "None"  # from python. make all the NULLs "None"?
  gct: NULL # not always used
  save_environ: false
---

<style type="text/css">
.main-container {
  max-width: 100% !important;
  margin: auto;
}
</style>

```{r setup, include=T}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages(library(rlang))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(magrittr))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(ComplexHeatmap))
suppressPackageStartupMessages(library(circlize))
suppressPackageStartupMessages(library(reactable))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(here))
library(dendsort)


library(knitr)
myreactable <- function(x, ...) reactable(x, defaultPageSize = 4, searchable = T, compact = T, resizable=T, sortable = T, filterable = T, ...)

(here())

source(file.path(here("R", "lazyloader.R")))

OUTDIR <- params$output_dir %||% params$data_dir %||% "."

util_tools <- get_tool_env("utils")
heatmap_utils <- get_tool_env("heatmap")

# source( file.path(here("R", "utils.R")), local = util_tools )
dist_no_na <- util_tools$dist_no_na
myzscore <- util_tools$myzscore
io_tools <- get_tool_env("io")

config <- io_tools$load_config(params$config) # if null returns defaults

knitr::opts_chunk$set(fig.path=file.path(OUTDIR, "modi-figures"))

SAVE_ENVIRON <- params$save_environ %||% FALSE

```

```
metadata should be a tsv file with an expr_file column
config can have an entry "batch" for application of batch correction
```


```{r}

fix_title <- function(x){
  x %>% basename() %>% gsub('_', ' ', .) %>% tools::file_path_sans_ext() %>% str_wrap(width = 24)
}


```


# load

params:
```{r, label=load_meta}
(params)

if (!is.null(params$metadata)){
    meta <- read_tsv(params$metadata, show_col_types = FALSE)
    if (!"group" %in% colnames(meta)) meta$group <- meta$name
} else {
  cat("no metadata passed, exiting")
  knitr::knit_exit()
}

OUTNAME <- basename(params$metadata) %>% gsub("_validated.tsv$", "", .)

```

```{r, label = view_meta}
meta %>% myreactable
```


```{r, label=load_expr}

if (!"expr_file" %in% colnames(meta)){
  cat("not implemented yet, exiting")
  knitr::knit_exit()
}

expr_files <- meta$expr_file %>% unique

datas <- expr_files %>%
    purrr::map( io_tools$read_expr )  # %>%
    purrr::set_names(expr_files)

( names(datas) )

```


```{r, label='combine data'}

data <- bind_rows(datas) # %>% dplyr::filter(!str_detect(protein, "\\|Cont_"))

# data %<>% distinct(sitename, ENSP, parent, fifteenmer, .keep_all = T)
# data %<>% distinct(sitename, parent, fifteenmer, hyperscore_best, .keep_all = T)

# dplyr::glimpse(data)

# data %>% head() %>% myreactable()

```


# explore


## counting


```{r, label='explore'}

data %>%
  distinct(spectra, .keep_all = T) %>%
  group_by(expr_file) %>%
  summarize(n = n()) %>%
  arrange(-n)

```


```{r}

data %>%
  distinct(spectra, .keep_all = T) %>% 
  mutate(expr_file = fix_title(expr_file)) %>%
  ggplot(mapping = aes(x=expr_file, y = hyperscore_best, fill = AA)) +
  geom_violin() +
  facet_wrap(~expr_file, scales = "free_x") +
  theme_minimal()
  

```



## counts
```{r}

.counts <- data %>%
  distinct(spectra, AA, .keep_all = T) %>%
  group_by(expr_file, AA) %>%
  summarize(n = n()) %>%
  arrange(-n) %>%
  ungroup

.counts %>%  
  mutate(expr_file = fix_title(expr_file)) %>%
  ggplot(aes(x = AA, y = n, fill = AA)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ expr_file, scales = "fixed", nrow=ceiling(length(unique(.counts$expr_file)) / 4)) +
  theme_minimal() +
  labs(title = "Max Spectral Count by Amino Acid", x = "Amino Acid", y = "Count")

```
```{r, label='barplot no ambiguity'} 

# Removing ambiguous sites
cleaned_data <- data %>%
  group_by(spectra) %>%
  filter(n_distinct(AA) == 1) %>%  # Keep only non-ambiguous spectra (those with one distinct AA)
  distinct(spectra, .keep_all = T) %>%
  ungroup()

# Re-run the summarization on the cleaned data
cleaned_plot_data <- cleaned_data %>%
  group_by(expr_file, AA) %>%
  summarize(n = n()) %>%
  arrange(-n)

# Re-plot the barplot
cleaned_plot_data %>%
  mutate(expr_file = fix_title(expr_file)) %>%
ggplot(mapping = aes(x = AA, y = n, fill = AA)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ expr_file, scales = "fixed", nrow=ceiling(length(unique(.counts$expr_file)) / 4)) +
  theme_minimal() +
  labs(title = "Non-Ambiguous Spectra Count by Amino Acid", x = "Amino Acid", y = "Count")

```
        


```{r, label='explore2'}
datal <- data %>%
  pivot_longer(
    cols = starts_with("TMT"), names_to = "expr_col"
  ) %>%
  inner_join(meta)

# datal %<>% dplyr::filter(!is.na(name))
# datal %>% dplyr::glimpse()
```

# normalize

```{r, label='normalize', cache=F}
# cacheing this is not working in Rmd
.minval <- datal %>%
  dplyr::filter(value > 0) %>%
  pull(value) %>%
  min()
datal %<>%
  dplyr::filter(value > 0) %>%
  group_by(name, recno, runno, searchno, label, taxon) %>%
  mutate(
    val_mednorm = (value + (.minval / 2)) / median(value, na.rm = T)
  ) %>%
  ungroup() %>%
  mutate(
    log2_val = log2(val_mednorm)
  )  %>%
  group_by(site_id) %>% mutate(zscore = util_tools$myzscore(log2_val)) %>% ungroup()

    
 
# counts <- datal %>%
#   dplyr::filter(!is.na(log2_val)) %>%
#   group_by(site_id, expr_file ) %>%
#   summarize(n=n()) %>%
#   arrange(-n)
# 
# keep <- 
# .counts$expr_file
# 
# 
# maxn <- min(max(counts$n), nrow(metadata))
# tokeep <- counts %>% filter(n >= maxn)
# datal %<>% dplyr::filter(
#   site_id %in% tokeep$site_id
# )
# 
  # (counts)
  # (maxn)
# datal %>% head() %>% myreactable()
datal %<>% util_tools$filter_observations(., "plex", .5)
```


```{r, eval=T, label='batch correction'}

do_combat <- function(datal, col="plex"){
  data_wide <- datal %>%
    pivot_wider(id_cols = site_id, names_from = name, values_from = log2_val)
  mat <- data_wide[, meta$name] %>% as.matrix
  rownames(mat) <-  data_wide$site_id
  .minval <- min(mat, na.rm = T)
  mat[is.na(mat)] <- .minval/2

  corrected_data <- sva::ComBat(dat = mat, batch = meta[[col]] %>% as.character )
}
if (!is.null(config$batch)){
  print("running combat")
  combat_corrected <- do_combat(datal, "plex")
  combat_corrected %<>% as.data.frame %>% rownames_to_column(var="site_id")
  combat_correctedl <- combat_corrected %>% pivot_longer(-site_id, values_to = 'log2_val')
  datal2 <- datal %>% dplyr::select(-log2_val) %>% left_join(combat_correctedl)
  datal <- datal2
  }

```

```{r, label='inspect data'}
( datal %>%   nrow() )
( datal %>%  distinct(spectra, .keep_all=T) %>% nrow() )
( datal %>%  distinct(name, spectra, .keep_all=T) %>% nrow() )
```

## distributions


```{r, label='distibrution1', fig.width=8}
datal %>%
  distinct(name, spectra, .keep_all=T) %>%
  ggplot(aes(x = log2_val, col = name)) +
  geom_density(alpha=.4) +
  facet_wrap(~group) +
  theme(legend.position="none")

```


```{r, label='distibrution2', fig.width=8}
datal %>%
  distinct(name, spectra, .keep_all=T) %>%
  ggplot(aes(x = log2_val, col = name)) +
  geom_density(alpha=.4) +
  facet_wrap(~expr_file) +
  theme(legend.position="none")
```



```{r, 'distribution3', fig.width=8}
datal %>%
  distinct(name, spectra, .keep_all=T) %>%
  ggplot(aes(x = log2_val, col = name)) +
  geom_density(alpha=.4) +
  facet_wrap(~expr_file+AA) +
  theme(legend.position="none")

```




```{r, label='pivot_wider'}
# .id_cols <- c("fifteenmer", "ENSG", "ENSP", "geneid", "taxon", "position", "sitename", "id", "modi_id")
#datal %>% dplyr::summarise(n = dplyr::n(), .by = c(fifteenmer, ENSG, ENSP, geneid, taxon, sitename, id, name))
dataw <- datal %>%
  pivot_wider(
    id_cols = site_id,
    names_from = name,
    #values_fn = function(x) median(x, na.rm = T),
    values_from = log2_val, # sometimes this happens after merging with phosphositeplus table
  )
dataw %>% write_tsv(file.path(OUTDIR, paste0(OUTNAME, "_modi_normed.tsv")))

gct <- datal %>% io_tools$create_gct_from_datal()

gct %>% cmapR::write_gct(file.path(OUTDIR, paste0(OUTNAME, "_modi_normed")))


if (SAVE_ENVIRON) save.image(file.path(OUTDIR$data_dir, 'merge_modis.RData'))


```


```{r, label='end'}
(params)
```

```{r, label='config'}
(config)
```
