---
title: "site-annotate-notreduced"
author: "MSPC"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    highlight: zenburn
    toc: yes
    toc_float: false
params:
  data_dir: NULL
  metadata: NULL
  modi_abbrev: p
---

<style type="text/css">
.main-container {
  max-width: 100% !important;
  margin: auto;
}
</style>


```{r setup, include=T}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages(library(rlang))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(magrittr))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(ComplexHeatmap))
suppressPackageStartupMessages(library(circlize))
suppressPackageStartupMessages(library(reactable))
library(knitr)
suppressPackageStartupMessages(library(here))

src_dir <- file.path(here("R"))
io_tools <- new.env()
source(file.path(src_dir, "./io.R"), local = io_tools)

reduce_tools <- new.env()
source(file.path(src_dir, "./reduce.R"), local = reduce_tools)

# Define a custom chunk hook
# not quite....
# knit_hooks$set(trycatch = function(before, options) {
#   if (before) {
#     # Before chunk execution, wrap in tryCatch
#     sprintf("tryCatch({\n")
#   } else {
#     # After chunk execution, close tryCatch and handle error
#     sprintf("}, error = function(e) { knitr::knit_exit() })\n")
#   }
# })

# Apply the custom hook to all chunks
# knitr::opts_chunk$set(trycatch = TRUE)

myreactable <- function(x, ...) reactable(x, defaultPageSize = 4, searchable = T, compact = T, ...)
```


# load
```{r}
(data_dir <- params$data_dir)

if (is.null(data_dir) | !fs::dir_exists(data_dir)) {
  (data_dir <- Sys.getenv("data_dir", unset = "."))
  if (is.null(data_dir)) {
    cat("data dir not set")
    knitr::knit_exit()
  }
}

print(data_dir)
```


```{r}
(files <- fs::dir_ls(data_dir, regexp = ".*notreduced.tsv$", fail = F, recurse = T))

if (length(files) == 0) {
  cat("no files found")
  knitr::knit_exit()
}


.names <- files %>% purrr::map(io_tools$set_name)
datas <- files %>%
  purrr::set_names(nm = .names) %>% # set names first
  purrr::map(~ {
    .table <- read_tsv(.x, show_col_types = F)
    return(.table)
  })

file_path_names <- files %>% as.list()
names(file_path_names) <- names(datas)

# datas %<>% purrr::map(
#   ~ {
#     .x %>% dplyr::filter(AA %in% c("S", "T", "Y"))
#   }
# )


extract_key_value_pairs <- io_tools$extract_key_value_pairs
input_string <- "ENSP|ENSMUSP00000001963|ENST|ENSMUST00000001963|ENSG|ENSMUSG00000020681|geneid|11421|taxon|10090|symbol|Ace|Ace"
(key_value_pairs <- extract_key_value_pairs(input_string))



.all_proteins <- datas %>%
  purrr::map(~ {
    .x %>%
      distinct(protein) %>%
      pull(protein)
  }) %>%
  unlist() %>%
  unique()
.res <- .all_proteins %>%
  purrr::map(
    extract_key_value_pairs
  )
.res <- set_names(.res, .all_proteins) # Ensure names are set for each element in the list
geneinfo <- .res %>%
  purrr::imap_dfr(~ {
    values <- .x
    original_str <- .y
    # Convert each named vector to a tibble (a transposed tibble for named vector handling)
    as_tibble(t(values)) %>%
      dplyr::mutate(protein = original_str) # Set the protein identifier using the name from the list
  })


geneinfo_counts <- geneinfo %>%
  pivot_longer(-protein) %>%
  group_by(name) %>%
  summarize(n = sum(!is.na(value)))
geneinfo_counts %<>% dplyr::filter(n > 1)
geneinfo %<>% dplyr::select(protein, all_of(geneinfo_counts$name))
geneinfo <- geneinfo %>%
  mutate(across(everything(), ~ replace_na(., "")))



datas %<>% purrr::map(
  ~ {
    .x %>% left_join(geneinfo)
  }
)
```


```{r}
names(datas)
```






# count

```{r}
datas[[1]] %>%
  # dplyr::filter(AA %in% c("S", "T", "Y")) %>%
  head(20) %>%
  dplyr::select(fifteenmer, protein, position_absolut, everything()) %>%
  myreactable()
```

## all counts

```{r}
# Group by 'AA' and count occurrences

aa_count <- datas[[1]] %>%
  distinct(fifteenmer, .keep_all = T) %>%
  group_by(AA) %>%
  summarize(sites = n())


aa_count <- datas %>%
  purrr::imap(
    ~ {
      .x %>%
        distinct(fifteenmer, .keep_all = T) %>%
        group_by(AA) %>%
        summarize(sites = n()) %>%
        mutate(id = .y)
    }
  ) %>%
  bind_rows()
aa_count %>%
  dplyr::select(id, AA, sites) %>%
  myreactable()
```

## probability above .75

```{r}
# Group by 'AA' and count occurrences

aa_count <- datas %>%
  purrr::imap(
    ~ {
      .x %>%
        distinct(fifteenmer, .keep_all = T) %>%
        dplyr::filter(prob > .75) %>%
        group_by(AA) %>%
        summarize(sites = n()) %>%
        mutate(id = .y)
    }
  ) %>%
  bind_rows()
aa_count %>%
  dplyr::select(id, AA, sites) %>%
  myreactable()
```



# plots

```{r}
# datas[[1]] %>% ggplot(aes(x = prob)) +
#   geom_histogram(binwidth = 0.01, fill = "#1c3079", color = "black") +
#   theme_minimal() +
#   labs(title = "Distribution of Prob", x = "Prob", y = "Count")

datas %>%
  purrr::imap(~ {
    .x %>%
      ggplot(aes(x = prob)) +
      geom_histogram(binwidth = 0.01, fill = "#1c3079", color = "black") +
      theme_minimal() +
      labs(title = paste0("Distribution of Prob", "\n", .y), x = "Prob", y = "Count")
  })
```


```{r}
datas %>%
  purrr::imap(~ {
    .x %>%
      ggplot(aes(x = charge)) +
      geom_bar(fill = "green", color = "black") +
      theme_minimal() +
      labs(title = paste0("Charge Counts", "\n", .y), x = "Prob", y = "Count")
  })
```



```{r}
datas %>%
  purrr::imap(~ {
    .x %>%
      ggplot(aes(x = intensity)) +
      geom_histogram(
        fill = "#1c3079", color = "grey50",
        binwidth = function(x) 2 * IQR(x) / (length(x)^(1 / 3))
      ) +
      theme_minimal() +
      labs(title = paste0("Distribution of Intensity", "\n", .y), x = "Intensity", y = "Count") +
      scale_x_log10() # Log scale for better visualization
  })
```


# reduce to site level

```{r}
# this is the 'non parallel' version:
# datas_reduced <- datas %>% purrr::map(
#   ~{
#     common_cols <- intersect(colnames(geneinfo), colnames(.x))  # Check against the first dataframe or ensure it's generalizable
#     .x %>%
#       head(1000) %>%
#       #group_by(fifteenmer, all_of(colnames(geneinfo))) %>%
#       group_by(fifteenmer, !!!rlang::syms(common_cols)) %>%
#       summarise(across(matches("TMT_.*intensity$"), sum, na.rm = TRUE), .groups = "drop")
#       # sum up all the columns that are of form TMT_xxx_x_intensity
#   }
# )


# n_workers <- future::availableCores() - 1
#
# future::plan(future::multisession, workers = n_workers)
# # from https://stackoverflow.com/a/69008715
# datas_reduced <- datas %>%
#   purrr::map(~{
#     common_cols <- intersect(colnames(geneinfo), colnames(.x))  # Check against the first dataframe or ensure it's generalizable
#     .data_chunks <- .x %>%
#       group_nest(fifteenmer, !!!rlang::syms(common_cols), .key = "grouped_data") %>%
#       dplyr::mutate(.worker_id = sample(1:n_workers, replace=T, size=nrow(.))) %>%
#       dplyr::group_split(.worker_id, .keep=F)
#     .data_chunks %>%
#       furrr::future_map_dfr(
#         function(.data) tidyr::unnest(.data, grouped_data) %>%
#           group_by(fifteenmer, !!!rlang::syms(common_cols)) %>%
#           summarise(out = across(matches("TMT_.*intensity$"), .fns = \(x) sum(x, na.rm = TRUE) )) %>%
#           ungroup() %>%
#           unnest(out)
#       )
#   }
#   )
#
# datas_reduced %<>% purrr::map( ~{
#   .newnames <- colnames(.x) %>% str_remove('_intensity')
#   colnames(.x) <- .newnames
#   return(.x)
#   } )
# datas_reduced[[1]] %>% head


datas_reduced <- reduce_tools$reduce_sites(datas, geneinfo)
```

```{r, label='add sitename'}
modi_abbrev <- params$modi_abbrev
# annotate with other info
possible_id_cols <- c("ENSG", "ENST", "ENSP", "geneid", "symbol", "taxon", "fifteenmer", "position_absolut", "AA", "sitename", "protein_length")
.metadatas <- datas %>% purrr::map(~ {
  common_cols <- intersect(colnames(.x), possible_id_cols)
  res <- .x %>%
    distinct(!!!rlang::syms(common_cols)) %>%
    mutate(sitename = stringr::str_c(symbol, stringr::str_c(!!modi_abbrev, AA, position_absolut), sep = "_"))
})
.metadata <- bind_rows(.metadatas) %>% distinct()

.datas_reduced <- datas_reduced %>% purrr::map(~ {
  common_cols <- intersect(colnames(.x), possible_id_cols)
  .x %>%
    left_join(.metadata) %>%
    dplyr::select(!!common_cols, everything())
})

.datas_reduced %<>% purrr::map(~ .x %>% rename(c("position" = "position_absolut")))
datas_reduced <- .datas_reduced
```


```{r}
# datas[[1]] %>% dplyr::filter(symbol == "H2BC21") %>% arrange(position) %>%
#   select(position, position_absolut)
#
# .metadata %>% dplyr::filter(symbol == "H2BC21") %>% arrange(position_absolut)
datas_reduced[[1]] %>%
  dplyr::filter(symbol == "H2BC21") %>%
  select(sitename, fifteenmer, geneid, symbol, taxon, position, everything()) %>%
  arrange(position)
```

## isoform reduction
```{r, label='load package data'}
package_data_dir <- file.path(here(), "/data")

(package_files <- fs::dir_ls(package_data_dir, glob = "*selection.mapping.txt", fail = F, recurse = T))
isoform_table <- package_files %>%
  purrr::map(~ read_tsv(.x, show_col_types = F)) %>%
  bind_rows()
```


```{r}
datas_reduced_withisoind <- datas_reduced %>%
  purrr::map(~ {
    df <- .x
    if (!"ENSP" %in% names(df)) {
      return(df) # cannot do
    }
    res <- left_join(df, isoform_table, by = c("ENSP" = "Protein_id", "ENSG" = "Gene_id"))
  })




condense_group <- function(df) {
  # Early exit if the data frame is empty
  if (nrow(df) == 0) {
    return(list(
      Protein_Accessions = NA,
      AApos_List = NA,
      Primary_select = NA,
      Secondary_select = NA,
      Unique_select = NA,
      Best_select = NA,
      Protein_Accession_Selected = NA,
      Reason_Selected = NA
    ))
  }

  # Handle NAs and create protein lists
  df$Primary_select <- ifelse(is.na(df$Primary_select), "", df$Primary_select)
  df$Secondary_select <- ifelse(is.na(df$Secondary_select), "", df$Primary_select)
  df$ENSP <- ifelse(is.na(df$ENSP), "", df$ENSP)
  proteins <- paste(unique(df$ENSP), collapse = ";")
  aapos_list <- paste(as.character(df$position), collapse = ";")

  # Processing selections
  primarysel <- if (any(df$Primary_select == "Yes")) {
    .val <- df$ENSP[df$Primary_select == "Yes"] %>% unique()
    paste(.val, collapse = ";")
  } else {
    NA
  }

  secondarysel <- if (any(df$Secondary_select == "Yes")) {
    .val <- df$ENSP[df$Secondary_select == "Yes"] %>% unique()
    paste(.val, collapse = ";")
  } else {
    NA
  }

  # Determine best and unique selections
  uniquesel <- NA
  bestsel <- NA
  if (is.na(primarysel) && is.na(secondarysel)) {
    if (length(unique(df$ENSP)) == 1) {
      uniquesel <- proteins
    } else if (length(unique(df$ENSP)) > 1) {
      bestsel <- df[which.max(df$protein_length), "ENSP"][[1, 1]]
    }
  }

  # Final selection logic
  finalsel <- if (!is.na(primarysel)) {
    primarysel
  } else if (!is.na(secondarysel)) {
    secondarysel
  } else if (!is.na(uniquesel)) {
    uniquesel
  } else {
    bestsel
  }
  reason <- if (!is.na(primarysel)) {
    "primary"
  } else if (!is.na(secondarysel)) {
    "secondary"
  } else if (!is.na(uniquesel)) {
    "not primary or secondary, only one choice"
  } else if (!is.na(bestsel)) {
    "not primary or secondary, multiple choices, returning longest"
  } else {
    NA
  }

  # Create output
  output <- list(
    Protein_Accessions = proteins,
    AApos_List = aapos_list,
    Primary_select = ifelse(is.na(primarysel), "", primarysel),
    Secondary_select = ifelse(is.na(secondarysel), "", secondarysel),
    Unique_select = ifelse(is.na(uniquesel), "", uniquesel),
    Best_select = ifelse(is.na(bestsel), "", bestsel),
    Protein_Accession_Selected = finalsel,
    Reason_Selected = reason
  )
  return(output)
}

# df <- datas_reduced_withisoind[[1]] %>% filter(fifteenmer == "RPKPSSsPVIFAGGQ" & ENSG == "ENSG00000197111")
# .a1 = 'AAQSPPsPASAEALL'
# .a2 = '283638'
# .a3 = 'ENSG00000099814'
# df <- datas_reduced_withisoind[[1]] %>% filter(fifteenmer == .a1 & ENSG == .a3)
# df <- datas_reduced_withisoind[[1]] %>% filter(fifteenmer == "AAAAAAsGVTTGKPP", geneid == "11129", ENSG == "ENSG00000104859")
# df <- datas_reduced_withisoind[[1]] %>% filter(fifteenmer == "AAAAAHsTPVRREVT", geneid == "23136", ENSG == "ENSG00000082397")
# df <- datas_reduced_withisoind[[1]] %>% filter(fifteenmer == "AESPETsAVESTQST", geneid == "100710" )
.res <- bind_rows(datas_reduced_withisoind) %>%
  group_by(fifteenmer,
    geneid,
    ENSG,
    # position
    .add = TRUE
  ) %>%
  summarise(data_summary = list(condense_group(cur_data())), .groups = "drop")
isoform_selection <- .res %>% unnest_wider(data_summary)
```



# export
```{r, label='do export'}
datas_reduced %>% purrr::imap(~ {
  df <- .x
  name <- .y
  dfm <- left_join(df, isoform_selection)
  orig_path <- file_path_names[[name]]
  rootdir <- fs::path_dir(orig_path)

  newfile <- fs::path_join(c(rootdir, paste0(str_replace(.y, "notreduced", "reduced"), ".tsv")))
  # print(orig_path)
  print(newfile)
  ._ <- readr::write_tsv(dfm, newfile)
})
```


